# API specifications settings
api:
  docs:
    auth:
      password: ''
      username: ''
    root: 'swagger'
    versions:
      - default_host: ''
        description: 'File Parser Docs'
        endpoint: 'v1/swagger.yaml'
        id: 'v1/swagger.yaml'
        openapi: '3.0.3'
        title: 'File Parser'
        version: 'v1'
  schemas:
    error_response:
      type: 'object'
      properties:
        error:
          $ref: '#/components/schemas/exception'
      required:
        - 'error'
    exception:
      type: 'object'
      properties:
        id:
          type: 'string'
        message:
          type: 'string'
    user:
      type: 'object'
      properties:
        user:
          type: 'object'
          properties:
            email:
              type: 'string'
            created_at:
              type: 'string'
              format: 'date-time'
            updated_at:
              type: 'string'
              format: 'date-time'
    attach_file_schema:
      type: object
      properties:
        file:
          type: string
          format: binary
      required:
      - file
    transaction:
      type: 'object'
      properties:
        transaction_type:
          type: 'string'
        date:
          type: 'string'
          format: 'date-time'
        value:
          type: 'string'
        cpf:
          type: 'string'
        time:
          type: 'string'
          format: 'date-time'
        store_id:
          type: 'string'
        created_at:
          type: 'string'
          format: 'date-time'
        updated_at:
          type: 'string'
          format: 'date-time'
    stores:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          owner:
            type: string
          total_balance:
            type: number
          created_at:
            type: string
            format: date-time
          updated_at:
            type: string
            format: date-time
          transactions:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                transaction_type:
                  type: integer
                date:
                  type: string
                  format: date
                value:
                  type: number
                cpf:
                  type: string
                card:
                  type: string
                time:
                  type: string
                  format: date-time
                store_id:
                  type: integer
                created_at:
                  type: string
                  format: date-time
                updated_at:
                  type: string
                  format: date-time
            
# CORS settings
cors:
  allowed_origins: '*'

# Database connection url
database:
  name: <%= ENV.fetch('DB_NAME') { nil } %>
  user: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  pass: <%= ENV.fetch('DB_PASS') { 'postgres' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>

secret_key: <%= ENV.fetch('SECRET_KEY') { '' } %>

# I18n Settings
i18n:
  available_locales:
    - en
    - pt-BR
  default_locale: 'pt-BR'
