services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-setup:
    build:
      context: ./api
    environment:
      RAILS_ENV: development
    command: bundle exec bin/rails db:prepare
    volumes:
      - ./api:/app
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db-setup
      - redis
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}

  sidekiq:
    build:
      context: ./api
    command: bundle exec sidekiq
    depends_on:
      - api
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./api:/app

volumes:
  postgres_data:
  redis_data:
